#' @title Compute Death Probabilities for a Specified Cohort at a Specified Age
#'
#' @description Calculates the probability of death for a user-specified cohort and a user-specified age.
#' The formula used can be found at tinyurl.com/demograsource.
#'
#' For example, the question 'what was the probability of death at age 1 for the cohort born in 1995?' can be answered with this function.
#' This would be computed as the number of people in that cohort who died at age 1 divided by the number that reached their 1st birthday.
#'
#' The function requires a data frame that contains variables for:
#'
#' - date of birth in century month code
#'
#' - survival status
#'
#' - survival time, as can be generated by the mortDHS_obs_time function in this package.
#'
#' @param data The relevant data frame
#' @param age The age for which the statistic is desired
#' @param cohort The cohort for which the statistic is desired
#' @param surv_stat String name for the column containing survival status. Requires that deceased is coded as 0, and alive is coded as 1. Defaults to 'mm2', the original DHS variable name.
#' @param DOB_CMC String name for column containing dates of birth in century month code. Defaults to 'mm4', the original DHS variable name.
#' @param obs_time String name for the column containing observation times, as can be generated by the mortDHS_obs_time function. Defaults to 'obs_time'
#'
#' @seealso \code{\link[mortDHS]{death_prob_cohort_range}}
#'
#' @return A single numerical value
#' @export
#' @examples
#' # compute probability of death at age 0 for the cohort born in 2000
#' death_prob_cohort(malawisib, 0, 2000)
#'
#' # same example as above, with each parameter more explicitly defined
#' death_prob_cohort(data = malawisib, age =0, cohort = 2000,
#' DOB_CMC = 'mm4', surv_stat = 'mm2', obs_time = 'obs_time')

death_prob_cohort <- function(data, age, cohort , surv_stat = 'mm2', DOB_CMC ='mm4', obs_time = 'obs_time'){

  # see Chapter 2 of the resource at  tinyurl.com/demograsource for further explanation of the formula used

  # convert cohort to CMC
  lower_lim_spec_age_in_months <- age * 12
  upper_lim_spec_age_in_months <- (age * 12) + 11

  cohort_lower_limit_CMC <- ((cohort - 1900) * 12 ) + 1
  cohort_upper_limit_CMC <-  ((cohort - 1900) * 12) + 12

  numerator <- sum( # count of individuals
    (data[[DOB_CMC]] >= cohort_lower_limit_CMC
     &data[[DOB_CMC]] <= cohort_upper_limit_CMC)
    # from the relevant cohort. These are folks who were born btw January and December of the specified year
    & (data[[surv_stat]] == 0 &
         data[[obs_time]] >= lower_lim_spec_age_in_months &
         data[[obs_time]] <= upper_lim_spec_age_in_months ), na.rm = TRUE )
  # who died at the specified age

  denominator <- sum(# count of individuals
    (data[[DOB_CMC]] >= cohort_lower_limit_CMC
     &data[[DOB_CMC]] <= cohort_upper_limit_CMC)
    # from the relevant cohort
    & (( data[[surv_stat]] == 1 & data[[obs_time]] >= lower_lim_spec_age_in_months)
       # who are alive and lived past the specified age
       |(data[[surv_stat]] == 0 & data[[obs_time]] >= lower_lim_spec_age_in_months)), na.rm = TRUE)
  # or deceased but died past the specified age

  return(numerator/denominator)

}



